#!/usr/local/bin/ruby

# @date November 20, 2016
# @author Dominic Philip
# @abstract Marker: A simple GitHub flavored markdown renderer
# @version 0.1


require 'webrick'
require 'github/markup'

if ARGV[0].nil?
  puts 'Please provide the markdown file or an argument'
  abort
end

path = File.dirname(File.expand_path(ARGV[0])) + '/index.html'

unless path.nil?
  File.open(path, 'w+') do |file|
    file.write(GitHub::Markup.render(ARGV[0], File.read(ARGV[0])))
  end
end


server = WEBrick::HTTPServer.new :Port => 8080, :DocumentRoot => path

trap 'INT' do server.shutdown end

server.start
